### ISSUE TITLE
[Feature Request] Multiple jump entries for the same query

### ISSUE THREAD

**Issue by kohane27** [cbochs/portal.nvim#17]
Hello cbochs! Thank you so much for creating such as awesome plugin for jumplist. I can see the tremendous value for using `portal.nvim` to have one unified interface to jump between different windows/changes/locations. Please see below for my humble feature request.

Desired behavior:

1. Open `portal.lua`
2. Open `legendary.lua`
3. Open `nvim-surround.lua`
4. Open `neozoom.lua` <- current window

Current jumps:

![2022-12-16-16-40-27](https://user-images.githubusercontent.com/57322459/208069487-fd579d08-c293-4e20-ab9c-e392e719afa0.png)

5. Trigger portal
6. Under the "Different" query box, we'd have multiple jump options to jump back to a more previous window (i.e., in this case, `nvim-surround.lua`, `legendary.lua` and `portal.lua`) Current implementation is that we can only jump to `nvim-surround.lua` (last window before the jump to `neozoom.lua`)

To make sure I didn't miss anything, I've looked into the src and found the following in `lua/portal/jump.lua`:

```lua
--- Given an list of jump queries: `{ "valid", "valid", "modified" }`,
--- the resulting ordered list will be:
--- * the first jump will be associated with the first item in the jumplist
--- * the second jump will be associated with the second item in the jumplist
--- * if the first jump was also modified, the third jump will also be
---   associated with the first item in the jumplist
```

Therefore, I achieved what I want with the following:

```lua
portal.setup({
  query = { "different", "different", "different", "different" },
  portal = {
    title = {
      render_empty = false,
    },
  },
})
```

![2022-12-16-17-32-18](https://user-images.githubusercontent.com/57322459/208069543-db635456-35c9-4191-a37e-a1bd72a98910.png)

However, it feels a hacky solution and I can't jump back to more than previous 4 locations unless I keep expanding the `query` table above. It'd be awesome if we could specify the number of jumps in the config (say, `max_different_entry`), and the UI would render the `max_different_entry` jump locations for each query.

Thank you!

**Comment by cbochs** [comment]
Hi @kohane27, thanks for creating the feature request!

This is an interesting topic to discuss.

The original design of this plugin was around the thought that users would never want more than a handful of results (e.g. a maximum of 4) to open portals for. With this design, a simple table expressing a "query" was sufficient.

However, pondering your proposal some more, I do feel like there's another potential use-case. That is, users may want to "filter" the jumplist to obtain all the jumps that fit a criterion. I.e. with your example above, use `"different"` to get all the uniquely "different" jumps and present them to the user.

With that said, I might propose a different approach to the one above. Instead of adding a `max_different_query` (or a setting similar to), create a "filter" that would yield all the jumps that match a given predicate. Then, present some setting - like `max_portals` - so that only a subset of jumps would be presented to the user in the form of portals. This has the added benefit that the "filtered" jump list could (possibly) be sent to something like the quickfix list.

What are your thoughts?

**Comment by cbochs** [comment]
@kohane27 #22 introduces a full rewrite of portal.nvim. One of the new features added is the ability to use more than one list for a single search. See the [Portal API](https://github.com/cbochs/portal.nvim#portal-api) for more details.

Closing this FR as done 🙂
