### ISSUE TITLE
[Feature Request] Jumping to changes from `change list`

### ISSUE THREAD

**Issue by kohane27** [cbochs/portal.nvim#18]
Hello cbochs! Hope you're doing well. Hope you don't mind that I submitted two feature requests in one day.

Currently, according to [Available Query Items](https://github.com/cbochs/portal.nvim#available-query-items), we have queries for `valid`, `different`, `modified` and `custom`. I'm wondering if it's possible to add `change` (as in change list) to either the built-in query or being a custom query? I thought adding change list to `portal.nvim` might be out of scope, but I see the integration with `grapple.nvim` and `harpoon`, so I thought I'd still suggest and see what you think.

For example, given the following change list:

```
  change line  col text
     3     9    8 bla bla bla
     2    11   57 foo is a bar
     1    14   54 the latest changed line
  >
```

Currently, if I want to jump back to 1st change (line 9 from example), I'd have to spam `g;` 3 times. To me, it's the same problem with spamming `C-o` to go back to the previous window. It'd be awesome if `portal.nvim` provides a query to jump back to a specific change list location, i.e, we may have a `change` query (like `different` or `modified`) and have a list of changelist history that we can jump back:

![2022-12-16-17-57-29](https://user-images.githubusercontent.com/57322459/208129987-35f3ada9-c280-4b40-abaa-9ef687f905af.png)

Note: Multiple jump entries for the same query is from https://github.com/cbochs/portal.nvim/issues/17

I found lewis6991's [jump.lua](https://github.com/lewis6991/dotfiles/blob/main/config/nvim/lua/lewis6991/jump.lua) for inspiration. Basically it shows a UI when jumping through the jumplist.

[My modified jump.lua](https://gist.github.com/kohane27/0c6088c8f146c9c8312061cd05b05dcc). I've removed all the unnecessary UI rendering (because we'd need to incorporate into `portal.nvim`). I think the most relevant is just the following:

```lua
  local changelist, last_jump_pos = unpack(vim.fn.getchangelist())
  local changelistResult = vim.inspect(changelist)
  vim.notify(changelistResult)
```

I'd love to hear what you think. Thank you!

**Comment by cbochs** [comment]
These are great feature requests. I don't mind at all 🙂

I think what you're getting at here is a request to better abstract "portals" from *lists (jumplist, changelist, marklist, qflist, loclist, etc) since currently it's pretty closely tied to the jumplist. This is certainly possible and I think is a great move to make Portal more flexible.

A couple initial notes:
* most vim lists conform to having a `lnum` and `col` field (except for [`:h getmarklist()`](https://neovim.io/doc/user/builtin.html#getmarklist()))
* some lists are directional and have a "current location" (i.e. the jumplist), some are just plain lists (i.e. the marklist)
* lists can be global (marklist), window-local or tab-local (jumplist), or buffer-local (changelist)

On the plugin side:
* What's the best way to expose these as part of the Portal API?
* How could Portal provide "sane defaults" for this?

I'm thinking that this could be expressed as something like this as the core of the Portal API (keep in mind that this is more like pseudo-code for now):

```lua
---@class Portal.Options
---@field query Portal.Query | Portal.Query[] | Portal.Filter
---@field list Portal.List | Portal.ListFunction
---@field direction? Portal.Direction

---Opens a number of portals for the user to choose from
---@param opts Portal.Options
require("portal").choose({
    query     = { require("portal").queries.different },
    list      = require("portal").lists.jumplist,
    direction = "backward" -- or "forward"
})

---Searches a list attempting to find jump locations based
---on an input query
---@param opts Portal.Options
---@return Portal.Location[]
require("portal").search({
    query     = require("portal").filters.none,
    list      = require("portal").lists.jumplist,
    direction = "backward"
})
```

Where:
* The input `query` can be a single query, a list of queries, or a filter (as proposed in #17)
* The input `list` could be as simple as providing the `vim.fn.getjumplist` function. I'm thinking it might be good to wrap it a bit
* The input `direction` would be required for directional lists

Each bullets above are just some design considerations and the above pseudo-code is mostly just to help understand how a user might use the API. Happy to hear feedback or any thoughts / ideas you have.

**Comment by cbochs** [comment]
@kohane27 #22 Adds the capability to implement a query for any list, including the changelist. This is not available as a builtin yet, but should be soon!

**Comment by kohane27** [comment]
@cbochs Thank you so very much for fulfilling my feature request!
Friday present came early! I'll check out the new Portal API and hopefully I can implement it.
btw, I'm very sorry that I didn't reply to your earlier comment. I tried implementing it but then dropped it, altogether with the conversation.

**Comment by cbochs** [comment]
No problem at all!

I've taken a quick crack at implementing the changelist. Feel free to try it out using the [`feat_changelist`](https://github.com/cbochs/portal.nvim/tree/feat_changelist) branch. The commands are `:Portal changelist [direction]` or via API with `require("portal.builtin").changelist`.

Let me know what you think 🙂

**Comment by cbochs** [comment]
@kohane27 Support for the `changelist` is now available in the latest release
