### ISSUE TITLE
First invocation error

### ISSUE THREAD

**Issue by prgres** [cbochs/portal.nvim#20]
Hello, 
I receive this error everytime I invoke `require("portal").jump_backward`. After that it works as it should. I had changed `log_level` to error but without a luck. I tried with the `setup` function and without.

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/23465248/214711760-8e2c65f8-ee00-4815-b6f6-19451b0a6a33.png">

**Comment by cbochs** [comment]
This might be related to a swapfile already existing for that buffer. See:
* https://groups.google.com/g/vim_dev/c/rLPQh1LGnG4?pli=1
* https://askubuntu.com/questions/1036030/e325-attention-swap-file-already-present-error-in-vi

This should be fixed with https://github.com/cbochs/portal.nvim/commit/2b9f5d957195059addb32b9e8e4aa09dad0cb3a8.

**Comment by cbochs** [comment]
Closing this as completed. If you're seeing this issue, feel free to reopen!

**Comment by prgres** [comment]
@cbochs seems like it works properly, thanks!
